#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep "\.js$")
if [ "$files" = "" ]; then
    exit 0
fi

dir=$(git rev-parse --git-dir)/../goonrak
pass=true

echo "\nValidating Scripts\n"

for file in ${files}; do
    result=$(${dir}/eslint --config ${dir}/.eslintrc ${file} | grep "error")
    if [ "$result" != "" ]; then
        echo "\t\033[31mESLint Failed ${file}\033[0m"
        pass=false
    fi
done

echo "\nScript validation complete\n"

if ! $pass; then
    echo "\033[41mCOMMIT FAILED\033[0m"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
